version: "3.9"
   
services:  
  tab_scrob:
    build: ${SCROBBLE_BUILD_TARGET}
    environment:
      # BigQuery variables
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - PROJECT_ID=${PROJECT_ID}
      - DATASET_ID=${DATASET_ID}
      - TABLE_ID=${TABLE_ID}
      # last.fm variables
      - LASTFM_USERNAME=${LASTFM_USERNAME}
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - PAGE_RETRIEVE_COUNT=2
      # Bind mount targets
      - LOGS_TARGET=${LOGS_TARGET}
      - SCROBBLE_TARGET=${SCROBBLE_TARGET}
      - MAPPER_TARGET=${MAPPER_TARGET}
    volumes:
      # Logging
      - type: bind
        source: ${LOGS_SOURCE}
        target: ${LOGS_TARGET}
        read_only: ${LOGS_TARGET_RO}
      # BigQuery Credentials
      - type: bind
        source: ${BQ_SOURCE}
        target: ${GOOGLE_APPLICATION_CREDENTIALS}
        read_only: ${BQ_RO}
      # Host scrobble Save Directory
      - type: bind
        source: ${SCROBBLE_SOURCE}
        target: ${SCROBBLE_TARGET}
        read_only: ${SCROBBLE_RO}     
      # Mapper
      - type: bind
        source: ${MAPPER_SOURCE}
        target: ${MAPPER_TARGET}
        read_only: ${MAPPER_RO}
